### ISSUE TITLE
Type of attention mechanism

### ISSUE THREAD

**Issue by olfaa** [junyongyou/Attention-boosted-deep-networks-for-video-classificaton#2]
Please can you provide which type of attention mechanism that used in your model.

**Comment by junyongyou** [comment]
> 
> 
> Please can you provide which type of attention mechanism that used in your model.

Hi, I simply used the self-attention mechanism in the dot product approach.

**Comment by olfaa** [comment]
Hi, I'm beginner in deep learning task and i want to know if it is a difference between self-attention mechanism in the dot product approach and self-attention. Thank you in advance

**Comment by junyongyou** [comment]
> 
> 
> Hi, I'm beginner in deep learning task and i want to know if it is a difference between self-attention mechanism in the dot product approach and self-attention. Thank you in advance

No, their is no difference. Dot-product is just one of the approaches to implement self attention.

**Comment by olfaa** [comment]
Hi
In which case we can use self-attention and global attention

**Comment by junyongyou** [comment]
> 
> 
> Hi
> In which case we can use self-attention and global attention

Please refer to relevant papers, e.g., "Attention is all you need".
